package com.dl.mapper;

import com.dl.pojo.Advice;
import com.dl.pojo.AdviceExample;
import com.dl.pojo.User;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    long countByExample(AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int deleteByExample(AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int insert(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int insertSelective(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    List<Advice> selectByExample(AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    Advice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Advice record, @Param("example") AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByExample(@Param("record") Advice record, @Param("example") AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByPrimaryKeySelective(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByPrimaryKey(Advice record);
    
    public List<Advice> findByPage(int page,int size);
	int getCount();
	public List<Advice> findByNamePage(@Param("title")String title, @Param("cpage")int cpage, @Param("size")int size);
	int getNameCount(String title);
}