package com.dl.mapper;

import com.dl.pojo.Charts;
import com.dl.pojo.ChartsExample;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

public interface ChartsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    long countByExample(ChartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int deleteByExample(ChartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int insert(Charts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int insertSelective(Charts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    List<Charts> selectByExample(ChartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    Charts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Charts record, @Param("example") ChartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByExample(@Param("record") Charts record, @Param("example") ChartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByPrimaryKeySelective(Charts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charts
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByPrimaryKey(Charts record);
    @Delete("delete from charts where id in(${value})")
	void deleteByIds(String newids);
    @Update("update charts set num=#{num} where id=#{id}")
	void updateNumById(Charts c);
}