package com.dl.mapper;

import com.dl.pojo.Orderitems;
import com.dl.pojo.OrderitemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderitemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    long countByExample(OrderitemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int deleteByExample(OrderitemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int insert(Orderitems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int insertSelective(Orderitems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    List<Orderitems> selectByExample(OrderitemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    Orderitems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Orderitems record, @Param("example") OrderitemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByExample(@Param("record") Orderitems record, @Param("example") OrderitemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByPrimaryKeySelective(Orderitems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    int updateByPrimaryKey(Orderitems record);
    List<Orderitems> findAll();
}