package com.dl.pojo;

public class Address {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column address.id
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column address.loc
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	private String loc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column address.uid
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column address.isDefault
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	private String isdefault;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column address.id
	 * @return  the value of address.id
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column address.id
	 * @param id  the value for address.id
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column address.loc
	 * @return  the value of address.loc
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	public String getLoc() {
		return loc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column address.loc
	 * @param loc  the value for address.loc
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	public void setLoc(String loc) {
		this.loc = loc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column address.uid
	 * @return  the value of address.uid
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column address.uid
	 * @param uid  the value for address.uid
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column address.isDefault
	 * @return  the value of address.isDefault
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	public String getIsdefault() {
		return isdefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column address.isDefault
	 * @param isdefault  the value for address.isDefault
	 * @mbg.generated  Sun Nov 17 23:45:19 CST 2019
	 */
	public void setIsdefault(String isdefault) {
		this.isdefault = isdefault;
	}

	@Override
	public String toString() {
		return "Address [id=" + id + ", loc=" + loc + ", uid=" + uid + "]";
	}
}