package com.dl.pojo;

public class Charts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charts.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer id;

    @Override
	public String toString() {
		return "Charts [id=" + id + ", gid=" + gid + ", num=" + num + ", uid=" + uid + ", goods=" + goods + "]";
	}
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charts.gid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charts.num
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charts.uid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charts.id
     *
     * @return the value of charts.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charts.id
     *
     * @param id the value for charts.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charts.gid
     *
     * @return the value of charts.gid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charts.gid
     *
     * @param gid the value for charts.gid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charts.num
     *
     * @return the value of charts.num
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charts.num
     *
     * @param num the value for charts.num
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charts.uid
     *
     * @return the value of charts.uid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charts.uid
     *
     * @param uid the value for charts.uid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

	public Charts(Integer id, Integer gid, Integer num, Integer uid) {
		super();
		this.id = id;
		this.gid = gid;
		this.num = num;
		this.uid = uid;
	}

	public Charts() {
		super();
		// TODO Auto-generated constructor stub
	}
    private Goods goods;

	public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}
    
}