package com.dl.pojo;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.miaoshu
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private String miaoshu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.color
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.newprice
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private Double newprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.oldprice
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private Double oldprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.ishot
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private String ishot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.isgood
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private String isgood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.isTuijian
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private String istuijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.num
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.salenum
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private Integer salenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.pic
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.parm
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    private String parm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.miaoshu
     *
     * @return the value of goods.miaoshu
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public String getMiaoshu() {
        return miaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.miaoshu
     *
     * @param miaoshu the value for goods.miaoshu
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setMiaoshu(String miaoshu) {
        this.miaoshu = miaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.color
     *
     * @return the value of goods.color
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.color
     *
     * @param color the value for goods.color
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.newprice
     *
     * @return the value of goods.newprice
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public Double getNewprice() {
        return newprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.newprice
     *
     * @param newprice the value for goods.newprice
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setNewprice(Double newprice) {
        this.newprice = newprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.oldprice
     *
     * @return the value of goods.oldprice
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public Double getOldprice() {
        return oldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.oldprice
     *
     * @param oldprice the value for goods.oldprice
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setOldprice(Double oldprice) {
        this.oldprice = oldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.type
     *
     * @return the value of goods.type
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.type
     *
     * @param type the value for goods.type
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.ishot
     *
     * @return the value of goods.ishot
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public String getIshot() {
        return ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.ishot
     *
     * @param ishot the value for goods.ishot
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setIshot(String ishot) {
        this.ishot = ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.isgood
     *
     * @return the value of goods.isgood
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public String getIsgood() {
        return isgood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.isgood
     *
     * @param isgood the value for goods.isgood
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setIsgood(String isgood) {
        this.isgood = isgood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.isTuijian
     *
     * @return the value of goods.isTuijian
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public String getIstuijian() {
        return istuijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.isTuijian
     *
     * @param istuijian the value for goods.isTuijian
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setIstuijian(String istuijian) {
        this.istuijian = istuijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.num
     *
     * @return the value of goods.num
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.num
     *
     * @param num the value for goods.num
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.salenum
     *
     * @return the value of goods.salenum
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public Integer getSalenum() {
        return salenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.salenum
     *
     * @param salenum the value for goods.salenum
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setSalenum(Integer salenum) {
        this.salenum = salenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.pic
     *
     * @return the value of goods.pic
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.pic
     *
     * @param pic the value for goods.pic
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.parm
     *
     * @return the value of goods.parm
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public String getParm() {
        return parm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.parm
     *
     * @param parm the value for goods.parm
     *
     * @mbg.generated Fri Oct 04 00:31:32 CST 2019
     */
    public void setParm(String parm) {
        this.parm = parm;
    }
}