package com.dl.pojo;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.loc
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private String loc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.type
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.loc
     *
     * @return the value of image.loc
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public String getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.loc
     *
     * @param loc the value for image.loc
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setLoc(String loc) {
        this.loc = loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.type
     *
     * @return the value of image.type
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.type
     *
     * @param type the value for image.type
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }
}