package com.dl.pojo;

public class Orderitems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.gid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.num
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.price
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.oid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer oid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.id
     *
     * @return the value of orderitems.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.id
     *
     * @param id the value for orderitems.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.gid
     *
     * @return the value of orderitems.gid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.gid
     *
     * @param gid the value for orderitems.gid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.num
     *
     * @return the value of orderitems.num
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.num
     *
     * @param num the value for orderitems.num
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.price
     *
     * @return the value of orderitems.price
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.price
     *
     * @param price the value for orderitems.price
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.oid
     *
     * @return the value of orderitems.oid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.oid
     *
     * @param oid the value for orderitems.oid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }
    private Goods goods;

	public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	@Override
	public String toString() {
		return "Orderitems [id=" + id + ", gid=" + gid + ", num=" + num + ", price=" + price + ", oid=" + oid
				+ ", goods=" + goods + "]";
	}
    
}