package com.dl.pojo;

import java.util.List;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
	
    private Integer id;

    @Override
	public String toString() {
		return "Orders [id=" + id + ", no=" + no + ", time=" + time + ", status=" + status + ", aid=" + aid
				+ ", paytype=" + paytype + ", uid=" + uid + ", address=" + address + ", user=" + user + ", oims=" + oims
				+ "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.no
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.time
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.aid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.paytype
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private String paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.uid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.no
     *
     * @return the value of orders.no
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.no
     *
     * @param no the value for orders.no
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.time
     *
     * @return the value of orders.time
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.time
     *
     * @param time the value for orders.time
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.aid
     *
     * @return the value of orders.aid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.aid
     *
     * @param aid the value for orders.aid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.paytype
     *
     * @return the value of orders.paytype
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.paytype
     *
     * @param paytype the value for orders.paytype
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.uid
     *
     * @return the value of orders.uid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.uid
     *
     * @param uid the value for orders.uid
     *
     * @mbg.generated Tue Sep 17 10:11:34 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    
    private Address address;
    private User user;
    private List<Orderitems> oims;
    
	public List<Orderitems> getOims() {
		return oims;
	}

	public void setOims(List<Orderitems> oims) {
		this.oims = oims;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
    
    
}