package com.dl.pojo;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.per_id
     *
     * @mbg.generated Thu Oct 10 11:27:36 CST 2019
     */
    private Integer perId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.per_name
     *
     * @mbg.generated Thu Oct 10 11:27:36 CST 2019
     */
    private String perName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.per_id
     *
     * @return the value of permission.per_id
     *
     * @mbg.generated Thu Oct 10 11:27:36 CST 2019
     */
    public Integer getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.per_id
     *
     * @param perId the value for permission.per_id
     *
     * @mbg.generated Thu Oct 10 11:27:36 CST 2019
     */
    public void setPerId(Integer perId) {
        this.perId = perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.per_name
     *
     * @return the value of permission.per_name
     *
     * @mbg.generated Thu Oct 10 11:27:36 CST 2019
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.per_name
     *
     * @param perName the value for permission.per_name
     *
     * @mbg.generated Thu Oct 10 11:27:36 CST 2019
     */
    public void setPerName(String perName) {
        this.perName = perName;
    }
}